### ISSUE TITLE
Can you provide other versions of WebRtcVad.dll?

### ISSUE THREAD

**Issue by CobraCalle** [ladenedge/WebRtcVadSharp#2]
Hi,

I`m writing a voice controller for my smart home and I would like to implement WebRTC-VAD for better voice detection... the room devices are running under linux. Could you provide and linux-arm-version of WebRtcVad.dll?

Thanks you very much

Carl

**Comment by ladenedge** [comment]
Sounds like a great idea.  I can work on this when I have time, but I'd also gladly accept a pull request!

**Comment by ladenedge** [comment]
There is now support for 32-bit Windows and ARM in the source.  I did not take the time to make packages for either platform yet, so anyone who wants to try it out will have to build it themselves.  If you do, please let me know how it works!

**Comment by Trunksome** [comment]
Hi there! I'm looking into making this library work on linux-x64; right now I'm trying to figure out how to compile a .dll for that platform. Where would I put it, once I have it? And is there a specific version of WebRTC that I need to build? Any pointers in the right direction are greatly appreciated @ladenedge :)
