### ISSUE TITLE
Unable to find WebRtcVad.dll

### ISSUE THREAD

**Issue by ADD-eNavarro** [ladenedge/WebRtcVadSharp#5]
I am using Visual Studio 2019 to detect speech in audio. I am using the NuGet package version 1.3.0 and when I try to create new WebRtcVad() I get this message:  "System.DllNotFoundException: 'Unable to load DLL 'WebRtcVad.dll' or a dependency. [...]"

**Comment by ladenedge** [comment]
Hm, yes, I see that this can happen when a platform is not explicitly set in the project's properties.  To get around this, you'll have to explicitly choose either **x86** or **x64** for your project.

![Platform properties](https://user-images.githubusercontent.com/2699775/113167854-572b2500-9201-11eb-80b0-7931867f0239.png)

I will add a warning to the build target that makes this clear.  Thanks for the report!

**Comment by ADD-eNavarro** [comment]
Yes, that solved the issue. Thank you!
